#include<stdio.h>
#include<math.h>
#include<string.h>
#include<stdlib.h>
int a[4][4]={{5,6,3,4},{1,7,2,8},{9,5,1,3},{2,1,4,6}};
main(){
    char c[1005];
    int i,j,tmp,b[4][4];
    scanf(" %s",c);
    for(i=0;i<strlen(c);i++){
        if(i%2==0){
            if(c[i]!='L'&&c[i]!='R'&&c[i]!='U'&&c[i]!='D'){
                printf("error");
                return 0;
            }
        }
        else if(i%2!=0){
            if(c[i]<'1'||c[i]>'4'){
                printf("error");
                return 0;
            }
        }
    }
    for(i=0;i<strlen(c);i++){
        if(c[i]=='L'){
            if(c[i+1]=='1'){
                for(j=0;j<4;j++){
                    b[0][j]=a[0][(j+1)%4];
                }
                for(j=0;j<4;j++){
                    a[0][j]=b[0][j];
                }
            }
            if(c[i+1]=='2'){
                for(j=0;j<4;j++){
                    b[1][j]=a[1][(j+1)%4];
                }
                for(j=0;j<4;j++){
                    a[1][j]=b[1][j];
                }
            }
            if(c[i+1]=='3'){
                for(j=0;j<4;j++){
                    b[2][j]=a[2][(j+1)%4];
                }
                for(j=0;j<4;j++){
                    a[2][j]=b[2][j];
                }
            }
            if(c[i+1]=='4'){
                for(j=0;j<4;j++){
                    b[3][j]=a[3][(j+1)%4];
                }
                for(j=0;j<4;j++){
                    a[3][j]=b[3][j];
                }
            }
        }
        if(c[i]=='R'){
            if(c[i+1]=='1'){
                for(j=0;j<4;j++){
                    b[0][j]=a[0][(j+3)%4];
                }
                for(j=0;j<4;j++){
                    a[0][j]=b[0][j];
                }
            }
            if(c[i+1]=='2'){
                for(j=0;j<4;j++){
                    b[1][j]=a[1][(j+3)%4];
                }
                for(j=0;j<4;j++){
                    a[1][j]=b[1][j];
                }
            }
            if(c[i+1]=='3'){
                for(j=0;j<4;j++){
                    b[2][j]=a[2][(j+3)%4];
                }
                for(j=0;j<4;j++){
                    a[2][j]=b[2][j];
                }
            }
            if(c[i+1]=='4'){
                for(j=0;j<4;j++){
                    b[3][j]=a[3][(j+3)%4];
                }
                for(j=0;j<4;j++){
                    a[3][j]=b[3][j];
                }
            }
        }
        if(c[i]=='U'){
            if(c[i+1]=='1'){
                for(j=0;j<4;j++){
                    b[j][0]=a[(j+1)%4][0];
                }
                for(j=0;j<4;j++){
                    a[j][0]=b[j][0];
                }
            }
            if(c[i+1]=='2'){
                for(j=0;j<4;j++){
                    b[j][1]=a[(j+1)%4][1];
                }
                for(j=0;j<4;j++){
                    a[j][1]=b[j][1];
                }
            }
            if(c[i+1]=='3'){
                for(j=0;j<4;j++){
                    b[j][2]=a[(j+1)%4][2];
                }
                for(j=0;j<4;j++){
                    a[j][2]=b[j][2];
                }
            }
            if(c[i+1]=='4'){
                for(j=0;j<4;j++){
                    b[j][3]=a[(j+1)%4][3];
                }
                for(j=0;j<4;j++){
                    a[j][3]=b[j][3];
                }
            }
        }
        if(c[i]=='D'){
            if(c[i+1]=='1'){
                for(j=0;j<4;j++){
                    b[j][0]=a[(j+3)%4][0];
                }
                for(j=0;j<4;j++){
                    a[j][0]=b[j][0];
                }
            }
            if(c[i+1]=='2'){
                for(j=0;j<4;j++){
                    b[j][1]=a[(j+3)%4][1];
                }
                for(j=0;j<4;j++){
                    a[j][1]=b[j][1];
                }
            }
            if(c[i+1]=='3'){
                for(j=0;j<4;j++){
                    b[j][2]=a[(j+3)%4][2];
                }
                for(j=0;j<4;j++){
                    a[j][2]=b[j][2];
                }
            }
            if(c[i+1]=='4'){
                for(j=0;j<4;j++){
                    b[j][3]=a[(j+3)%4][3];
                }
                for(j=0;j<4;j++){
                    a[j][3]=b[j][3];
                }
            }
        }
    }
    for(i=0;i<4;i++){
        for(j=0;j<4;j++){
            printf("%d ",a[i][j]);
        }
        printf("\n");
    }
    return 0;
}

